version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - sudo npm install -g npm@latest
      - sudo npm install -g @angular/cli@6.0.0
  build:
    commands:
      
      # run the build
      - sudo ng build --prod
artifacts:
  files:
    # bundle everything as a build artifact, except hidden files
    - '**/*'
