version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - sudo npm install -g npm@latest
      - sudo npm install -g @angular/cli@6.0.0
  build:
    commands:
      
      # run the build
      - cd/home/ubuntu/Angular-test
      - npm install --save-dev @angular-devkit/build-angular
      - sudo npm run build
artifacts:
  files:
    # bundle everything as a build artifact, except hidden files
    - '**/*'
